### ISSUE TITLE
'Join our Slack' link is dead

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/Website#88] opened 2017-11-09 20:34 UTC
https://democracyclub.org.uk/contact/

**Comment by symroe** [comment] 2017-11-10 17:50
This was caused by me converting our Heroku dyno from a hobby (paid for) to a free one. 

Apparently free dynos don't support SSL (or don't any more) so the https version broke. The http one was always working.

Should be fixed now, at a cost of $7/month. Maybe we should deploy this to another server somewhere? It's a tiny node script.

**Comment by symroe** [comment] 2017-11-10 17:51
It's odd because it was working earlier this week, but I converted it to free about 2 weeks ago.

**Closed by symroe** 2017-11-10 17:50 UTC

**Comment by chris48s** [comment] 2017-11-10 17:53
seems like quite a good candidate to live on AWS lamda?

**Comment by symroe** [comment] 2017-11-10 17:54
Can we SSL on Lamda? Via cloud front I guess?

Yep, something to try out!
