### ISSUE TITLE
Unable to respond to survey on YNMP

### ISSUE THREAD

**Issue by andylolz** [DemocracyClub/Website#12] opened 2015-04-28 09:27 UTC
when clicking anything on the first page of the survey, the chrome javascript console says:
```
research.min.js:5 Uncaught TypeError: Cannot read property 'close' of undefined
```

**Comment by symroe** [comment] 2015-04-28 13:48
This was caused by foundation messing with the version of jQuery in the research file.  Fixed now.

**Comment by andylolz** [comment] 2015-04-28 13:49
Fixed in DemocracyClub/YourNextMP-Read@3b696998

**Closed by symroe** 2015-04-28 13:48 UTC
