### ISSUE TITLE
The 2018 elections report has gone missing

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/Website#134] opened 2019-01-02 17:05 UTC
Whoops!

https://democracyclub.org.uk/report_2018/

**Comment by chris48s** [comment] 2019-01-13 20:18
I could not reproduce this locally, but looking at the logs in CloudWatch I think this is being caused by

`ValueError: The file 'report_2018/images/benjamin-elliott-670761-unsplash.jpg' could not be found with <core.s3_lambda_storage.StaticStorage object at 0x7fc8f441e0b8>.`

**Comment by symroe** [comment] 2019-02-13 19:01
Fixed in d0af4537a3e9af746184f20633d7b7d1eaa8c1f2

**Closed by symroe** 2019-02-13 19:01 UTC
